# Generated by Django 3.1.6 on 2021-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20210218_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default=1, upload_to='authors/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
