# Generated by Django 3.1.6 on 2021-02-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_author_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.ImageField(upload_to='books/', verbose_name='Обложка'),
        ),
    ]
