# Generated by Django 3.1.6 on 2021-02-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20210218_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(default=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Год издания'),
        ),
    ]
