# Generated by Django 3.1.6 on 2021-02-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_auto_20210218_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
