# Generated by Django 3.1.6 on 2021-02-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_quotes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.author', verbose_name='Автор'),
        ),
    ]
