# Generated by Django 3.1.6 on 2021-03-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_auto_20210227_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookfile',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
