# Generated by Django 3.1.6 on 2021-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0013_auto_20210303_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average',
            field=models.FloatField(default=1.0),
        ),
    ]
